@startuml

[*] --> MENU
MENU: 1. MAKANAN
MENU: 2. MINUMAN

MENU --> PILIH
PILIH: - JIKA PILIHAN MAKANAN
PILIH --> MAKANAN
MAKANAN: 1. NASI GORENG
MAKANAN: 2. LELE GORENG

MAKANAN --> HARGA
MAKANAN --> QTY
MAKANAN --> STOCK

PILIH: - JIKA PILIHAN MINUMAN
PILIH --> MINUMAN
MINUMAN: 1. ES TEH
MINUMAN: 2. ES DOGER

MINUMAN --> QTY
QTY --> INPUT
MINUMAN --> HARGA
HARGA --> INPUT
MINUMAN --> STOCK
STOCK --> INPUT
INPUT --> SUKSES
SUKSES --> [*]
INPUT --> FAILURE
STOCK --> EDIT
STOCK --> DELETE



@enduml