@baseUrl = http://127.0.0.1
@cType = application/json
@password = password

### GET DATA ALL PRODUCT
GET {{baseUrl}}/api/v1/product/
Content-Type: {{cType}}
Authorization: {{password}}

### INI BUAT GET DATA PRODUCT BY ID
GET {{baseUrl}}/api/v1/product/1
Content-Type: {{cType}}
Authorization: {{password}}

### INI BUAT INSERT DATA PRODUCT
POST {{baseUrl}}/api/v1/product
Authorization: {{password}}
Content-Type: {{cType}}

{
    "data": {
        "attributes": {
            "name": "Pensil",
            "price": 5000
        }
    }
}

### INI BUAT UPDATE DATA PRODUCT
PUT {{baseUrl}}/api/v1/product/1
Authorization: {{password}}
Content-Type: {{cType}}

{
    "data": {
        "attributes": {
            "name": "Pensil",
            "price": 5000
        }
    }
}

### MENGHAPUS DATA PRODUCT BY ID
DELETE {{baseUrl}}/api/v1/product/3
Authorization: {{password}}
Content-Type: {{cType}}