@baseUrl = http://127.0.0.1
@cType = application/x-www-form-urlencoded
@password = password

###
GET {{baseUrl}}

### GET DATA USER
GET {{baseUrl}}/api/v1/user
Content-Type: {{cType}}
Authorization: {{password}}